"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-6on4-j-uxor!d27!%kp3lhs8*7z(mh7aj!x63nmq*)9q8h@pyc'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'unfold',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "import_export",
    'common',
    'apps.courses',
    'apps.fees',
    'apps.leads',
    'apps.staff',
    'apps.students',
    'apps.tasks',
    'apps.teachers',
    'apps.dashboard',
    "apps.attendance",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"], 
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",  
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


WSGI_APPLICATION = 'config.wsgi.application'
AUTH_USER_MODEL = "staff.Staff"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'cict_db',
        'USER': 'cict_user',
        'PASSWORD': 'cict@123!!@@',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]



# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


def can(request, perm):
    user = request.user
    return user.is_authenticated and user.is_staff and user.has_perm(perm)




UNFOLD = {
    # --------------------
    # Site Branding
    # --------------------
    "SITE_TITLE": "Corporate Training",
    "SITE_HEADER": "Corporate Training Admin",
    "SITE_SUBHEADER": "Learning & Development",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": False,
    "SITE_URL": "/admin/",
    "SITE_ICON": {
        "light": "https://corusinfo.com/assets/images/LOGO[1]%201.png",
        "dark": "https://corusinfo.com/assets/images/LOGO[1]%201.png",
    },

    # --------------------
    # Sidebar Navigation
    # --------------------
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [

            # -------- Main --------
            {
                "title": "Main",
                "items": [
                    {
                        "title": "Dashboard",
                        "icon": "dashboard",
                        "link": "/admin/",
                        "permission": lambda r: r.user.is_authenticated,
                        "url_type": "absolute",
                    },
                ],
            },

            # -------- Management --------
            {
                "title": "Management",
                "items": [
                    {
                        "title": "Staff",
                        "icon": "group",
                        "link": "/admin/staff/staff/",
                        "permission": lambda r: can(r, "staff.view_staff"),
                        "url_type": "absolute",
                    },
                    {
                        "title": "Students",
                        "icon": "person",
                        "link": "/admin/students/student/",
                        "permission": lambda r: can(r, "students.view_student"),
                        "url_type": "absolute",
                    },
                ],
            },

            # -------- Financials --------
            {
                "title": "Financials",
                "items": [
                    {
                        "title": "Fee Management",
                        "icon": "payments",
                        "link": "/admin/fees/studentfee/",
                        "permission": lambda r: can(r, "fees.view_studentfee"),
                        "url_type": "absolute",
                    },
                ],
            },

            # -------- Leads --------
            {
                "title": "Leads",
                "items": [
                    {
                        "title": "Leads",
                        "icon": "contact_page",
                        "link": "/admin/leads/lead/",
                        "permission": lambda r: can(r, "leads.view_lead"),
                        "url_type": "absolute",
                    },
                ],
            },

            # -------- Academics --------
            {
                "title": "Academics",
                "items": [
                    {
                        "title": "Courses",
                        "icon": "menu_book",
                        "link": "/admin/courses/course/",
                        "permission": lambda r: can(r, "courses.view_course"),
                        "url_type": "absolute",
                    },
                    {
                        "title": "Attendance",
                        "icon": "event_available",
                        "link": "/admin/attendance/attendance/",
                        "permission": lambda r: can(r, "attendance.view_attendance"),
                        "url_type": "absolute",
                    },
                ],
            },
        ],
    },

    # --------------------
    # Dashboard Widgets
    # --------------------
    "DASHBOARD": {
        "enabled": True,
        "widgets": [
            "apps.dashboard.unfold.kpi_cards",
            "apps.dashboard.unfold.attendance_chart",
            "apps.dashboard.unfold.fee_collection_chart",
        ],
    },
}




ATTENDANCE_CUTOFF_HOUR = 10
ATTENDANCE_CUTOFF_MINUTE = 30
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'



