# Generated by Django 6.0 on 2026-01-04 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fees', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayment',
            name='collected_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'accounts'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feeledger',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='fees.feepayment'),
        ),
        migrations.AddField(
            model_name='studentfee',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fee_account', to='students.student'),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='student_fee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='fees.studentfee'),
        ),
        migrations.AddField(
            model_name='feeledger',
            name='student_fee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='fees.studentfee'),
        ),
        migrations.AddIndex(
            model_name='studentfee',
            index=models.Index(fields=['status', 'is_active'], name='fees_studen_status_703488_idx'),
        ),
        migrations.AddIndex(
            model_name='feeledger',
            index=models.Index(fields=['student', 'created_at'], name='fees_feeled_student_a94aa9_idx'),
        ),
    ]
